/**
 * fix-blog-db.ts — чинит автоинкремент id и добавляет языковые SEO-поля.
 *
 * Запуск из корня проекта:  npx tsx fix-blog-db.ts
 * Идемпотентен, ничего не удаляет. Можно запускать сколько угодно раз.
 *
 * Ошибка «null value in column "id" of relation "posts" violates not-null
 * constraint» означает, что у колонки id пропало значение по умолчанию —
 * автоинкремент. INSERT в коде id не передаёт и рассчитывает на базу.
 *
 * Миграция создаёт таблицу с `id SERIAL`, и первая статья сохранилась —
 * значит, автоинкремент был и его сняли позже. Так бывает, если таблицу
 * пересоздали через `CREATE TABLE ... AS SELECT` (бэкап/восстановление
 * переносит данные, но не DEFAULT, первичный ключ и индексы), или внешний
 * инструмент привёл схему к своему описанию, где автоинкремента нет.
 *
 * Скрипт проверяет не только posts, а все таблицы, куда пишет админка:
 * если слетело в одной, могло слететь и в других. В конце — отчёт.
 */

import 'dotenv/config';
import postgres from 'postgres';

const dbUrl = process.env.DATABASE_URL || process.env.DIRECT_URL;
if (!dbUrl) {
  console.error('❌ DATABASE_URL не найден. Запускайте из корня проекта.');
  process.exit(1);
}

const sql = postgres(dbUrl, { ssl: 'require', max: 1, prepare: false });

/** Таблицы, в которые админка делает INSERT без явного id. */
const TABLES = [
  'posts', 'post_tags',
  'producers', 'producer_applications', 'regions',
  'categories', 'subcategories', 'products', 'orders',
];

async function main() {
  console.log('⏳ Проверяю автоинкремент id…\n');

  const fixed: string[] = [];
  const ok: string[] = [];

  for (const table of TABLES) {
    const [col] = await sql`
      SELECT column_default, is_identity, data_type
      FROM information_schema.columns
      WHERE table_schema = 'public' AND table_name = ${table} AND column_name = 'id'
    `;

    if (!col) {
      console.log(`  · ${table} — таблицы нет, пропускаю`);
      continue;
    }

    const hasDefault = Boolean(col.column_default) || col.is_identity === 'YES';
    if (hasDefault) {
      ok.push(table);
      continue;
    }

    const [{ max }] = await sql.unsafe(`SELECT COALESCE(MAX(id), 0)::bigint AS max FROM ${table}`);
    const next = Number(max) + 1;

    // Обычно пропадает только DEFAULT, а старый счётчик от SERIAL остаётся
    // жив и привязан к колонке. Тогда восстанавливаем ровно исходное
    // состояние: возвращаем DEFAULT на этот же счётчик.
    //
    // Важно не создавать рядом второй, IDENTITY: при живом старом счётчике
    // pg_get_serial_sequence продолжает возвращать СТАРЫЙ, и выставить
    // значение новому через него нельзя — первая же запись получает id = 1
    // и падает на дубле. Проверено на тестовой базе.
    const [owned] = await sql`SELECT pg_get_serial_sequence(${table}, 'id') AS seq`;

    await sql.unsafe(`ALTER TABLE ${table} ALTER COLUMN id SET NOT NULL`);

    if (owned?.seq) {
      await sql.unsafe(`ALTER TABLE ${table} ALTER COLUMN id SET DEFAULT nextval('${owned.seq}'::regclass)`);
      await sql.unsafe(`SELECT setval('${owned.seq}'::regclass, ${next}, false)`);
    } else {
      // Счётчика нет совсем (таблицу пересоздали через CREATE TABLE AS) —
      // заводим IDENTITY и сразу ставим его за максимальный id.
      await sql.unsafe(`ALTER TABLE ${table} ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY`);
      await sql.unsafe(`ALTER TABLE ${table} ALTER COLUMN id RESTART WITH ${next}`);
    }

    fixed.push(table);
    console.log(`  ✓ ${table} — автоинкремент восстановлен`);
  }

  // Первичный ключ тоже мог потеряться вместе с DEFAULT.
  const noPk = await sql`
    SELECT t.table_name
    FROM information_schema.tables t
    WHERE t.table_schema = 'public'
      AND t.table_name = ANY(${TABLES})
      AND NOT EXISTS (
        SELECT 1 FROM information_schema.table_constraints c
        WHERE c.table_schema = 'public' AND c.table_name = t.table_name
          AND c.constraint_type = 'PRIMARY KEY'
      )
  `;
  for (const r of noPk) {
    try {
      await sql.unsafe(`ALTER TABLE ${r.table_name} ADD PRIMARY KEY (id)`);
      console.log(`  ✓ ${r.table_name} — первичный ключ восстановлен`);
    } catch (e: any) {
      console.log(`  ⚠ ${r.table_name} — не удалось добавить первичный ключ: ${e.message}`);
      console.log('     Вероятно, в таблице есть дубли id. Напишите — разберём.');
    }
  }

  // ── Языковые SEO-поля блога ─────────────────────────────────────────────
  console.log('\n⏳ Добавляю SEO-поля на английском и грузинском…');
  for (const c of ['seo_title_en', 'seo_title_ka', 'seo_description_en', 'seo_description_ka']) {
    await sql.unsafe(`ALTER TABLE posts ADD COLUMN IF NOT EXISTS ${c} text`);
  }
  console.log('  ✓ posts: seo_title / seo_description × en, ka');

  // ── Отчёт ───────────────────────────────────────────────────────────────
  console.log('\n🎉 Готово.');
  console.log(`   В порядке:       ${ok.join(', ') || '—'}`);
  console.log(`   Исправлено:      ${fixed.join(', ') || '—'}`);
  if (fixed.length > 1) {
    console.log('\n   Автоинкремент слетел сразу в нескольких таблицах — значит, их');
    console.log('   пересоздавали одним действием. Если запускали восстановление из');
    console.log('   бэкапа или db push из другого проекта — это оно.');
  }
}

main()
  .catch((e) => { console.error('❌ Ошибка:', e); process.exitCode = 1; })
  .finally(() => sql.end());
